// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gen_proto/test.proto

#ifndef PROTOBUF_INCLUDED_gen_5fproto_2ftest_2eproto
#define PROTOBUF_INCLUDED_gen_5fproto_2ftest_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_gen_5fproto_2ftest_2eproto 

namespace protobuf_gen_5fproto_2ftest_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_gen_5fproto_2ftest_2eproto
class FirstProtoBuf;
class FirstProtoBufDefaultTypeInternal;
extern FirstProtoBufDefaultTypeInternal _FirstProtoBuf_default_instance_;
namespace google {
namespace protobuf {
template<> ::FirstProtoBuf* Arena::CreateMaybeMessage<::FirstProtoBuf>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class FirstProtoBuf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FirstProtoBuf) */ {
 public:
  FirstProtoBuf();
  virtual ~FirstProtoBuf();

  FirstProtoBuf(const FirstProtoBuf& from);

  inline FirstProtoBuf& operator=(const FirstProtoBuf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FirstProtoBuf(FirstProtoBuf&& from) noexcept
    : FirstProtoBuf() {
    *this = ::std::move(from);
  }

  inline FirstProtoBuf& operator=(FirstProtoBuf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FirstProtoBuf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FirstProtoBuf* internal_default_instance() {
    return reinterpret_cast<const FirstProtoBuf*>(
               &_FirstProtoBuf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(FirstProtoBuf* other);
  friend void swap(FirstProtoBuf& a, FirstProtoBuf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FirstProtoBuf* New() const final {
    return CreateMaybeMessage<FirstProtoBuf>(NULL);
  }

  FirstProtoBuf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FirstProtoBuf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FirstProtoBuf& from);
  void MergeFrom(const FirstProtoBuf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FirstProtoBuf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string interface = 1;
  void clear_interface();
  static const int kInterfaceFieldNumber = 1;
  const ::std::string& interface() const;
  void set_interface(const ::std::string& value);
  #if LANG_CXX11
  void set_interface(::std::string&& value);
  #endif
  void set_interface(const char* value);
  void set_interface(const char* value, size_t size);
  ::std::string* mutable_interface();
  ::std::string* release_interface();
  void set_allocated_interface(::std::string* interface);

  // @@protoc_insertion_point(class_scope:FirstProtoBuf)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr interface_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_gen_5fproto_2ftest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FirstProtoBuf

// string interface = 1;
inline void FirstProtoBuf::clear_interface() {
  interface_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FirstProtoBuf::interface() const {
  // @@protoc_insertion_point(field_get:FirstProtoBuf.interface)
  return interface_.GetNoArena();
}
inline void FirstProtoBuf::set_interface(const ::std::string& value) {
  
  interface_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:FirstProtoBuf.interface)
}
#if LANG_CXX11
inline void FirstProtoBuf::set_interface(::std::string&& value) {
  
  interface_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:FirstProtoBuf.interface)
}
#endif
inline void FirstProtoBuf::set_interface(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  interface_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FirstProtoBuf.interface)
}
inline void FirstProtoBuf::set_interface(const char* value, size_t size) {
  
  interface_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FirstProtoBuf.interface)
}
inline ::std::string* FirstProtoBuf::mutable_interface() {
  
  // @@protoc_insertion_point(field_mutable:FirstProtoBuf.interface)
  return interface_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FirstProtoBuf::release_interface() {
  // @@protoc_insertion_point(field_release:FirstProtoBuf.interface)
  
  return interface_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FirstProtoBuf::set_allocated_interface(::std::string* interface) {
  if (interface != NULL) {
    
  } else {
    
  }
  interface_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), interface);
  // @@protoc_insertion_point(field_set_allocated:FirstProtoBuf.interface)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_gen_5fproto_2ftest_2eproto
