// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#include "test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class ietfdpdkDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ietfdpdk>
      _instance;
} _ietfdpdk_default_instance_;
namespace protobuf_test_2eproto {
static void InitDefaultsietfdpdk() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ietfdpdk_default_instance_;
    new (ptr) ::ietfdpdk();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ietfdpdk::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ietfdpdk =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsietfdpdk}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ietfdpdk.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ietfdpdk, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ietfdpdk, interface1_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ietfdpdk)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ietfdpdk_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "test.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ntest.proto\"\036\n\010ietfdpdk\022\022\n\ninterface1\030\001"
      " \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 52);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "test.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_test_2eproto

// ===================================================================

void ietfdpdk::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ietfdpdk::kInterface1FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ietfdpdk::ietfdpdk()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_test_2eproto::scc_info_ietfdpdk.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ietfdpdk)
}
ietfdpdk::ietfdpdk(const ietfdpdk& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  interface1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.interface1().size() > 0) {
    interface1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.interface1_);
  }
  // @@protoc_insertion_point(copy_constructor:ietfdpdk)
}

void ietfdpdk::SharedCtor() {
  interface1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ietfdpdk::~ietfdpdk() {
  // @@protoc_insertion_point(destructor:ietfdpdk)
  SharedDtor();
}

void ietfdpdk::SharedDtor() {
  interface1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ietfdpdk::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ietfdpdk::descriptor() {
  ::protobuf_test_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ietfdpdk& ietfdpdk::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_test_2eproto::scc_info_ietfdpdk.base);
  return *internal_default_instance();
}


void ietfdpdk::Clear() {
// @@protoc_insertion_point(message_clear_start:ietfdpdk)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  interface1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ietfdpdk::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ietfdpdk)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string interface1 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_interface1()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->interface1().data(), static_cast<int>(this->interface1().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ietfdpdk.interface1"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ietfdpdk)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ietfdpdk)
  return false;
#undef DO_
}

void ietfdpdk::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ietfdpdk)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string interface1 = 1;
  if (this->interface1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->interface1().data(), static_cast<int>(this->interface1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ietfdpdk.interface1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->interface1(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ietfdpdk)
}

::google::protobuf::uint8* ietfdpdk::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ietfdpdk)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string interface1 = 1;
  if (this->interface1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->interface1().data(), static_cast<int>(this->interface1().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ietfdpdk.interface1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->interface1(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ietfdpdk)
  return target;
}

size_t ietfdpdk::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ietfdpdk)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string interface1 = 1;
  if (this->interface1().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->interface1());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ietfdpdk::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ietfdpdk)
  GOOGLE_DCHECK_NE(&from, this);
  const ietfdpdk* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ietfdpdk>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ietfdpdk)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ietfdpdk)
    MergeFrom(*source);
  }
}

void ietfdpdk::MergeFrom(const ietfdpdk& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ietfdpdk)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.interface1().size() > 0) {

    interface1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.interface1_);
  }
}

void ietfdpdk::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ietfdpdk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ietfdpdk::CopyFrom(const ietfdpdk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ietfdpdk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ietfdpdk::IsInitialized() const {
  return true;
}

void ietfdpdk::Swap(ietfdpdk* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ietfdpdk::InternalSwap(ietfdpdk* other) {
  using std::swap;
  interface1_.Swap(&other->interface1_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ietfdpdk::GetMetadata() const {
  protobuf_test_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ietfdpdk* Arena::CreateMaybeMessage< ::ietfdpdk >(Arena* arena) {
  return Arena::CreateInternal< ::ietfdpdk >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
