// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_INCLUDED_test_2eproto
#define PROTOBUF_INCLUDED_test_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_test_2eproto 

namespace protobuf_test_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_test_2eproto
class ietfdpdk;
class ietfdpdkDefaultTypeInternal;
extern ietfdpdkDefaultTypeInternal _ietfdpdk_default_instance_;
namespace google {
namespace protobuf {
template<> ::ietfdpdk* Arena::CreateMaybeMessage<::ietfdpdk>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class ietfdpdk : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ietfdpdk) */ {
 public:
  ietfdpdk();
  virtual ~ietfdpdk();

  ietfdpdk(const ietfdpdk& from);

  inline ietfdpdk& operator=(const ietfdpdk& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ietfdpdk(ietfdpdk&& from) noexcept
    : ietfdpdk() {
    *this = ::std::move(from);
  }

  inline ietfdpdk& operator=(ietfdpdk&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ietfdpdk& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ietfdpdk* internal_default_instance() {
    return reinterpret_cast<const ietfdpdk*>(
               &_ietfdpdk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ietfdpdk* other);
  friend void swap(ietfdpdk& a, ietfdpdk& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ietfdpdk* New() const final {
    return CreateMaybeMessage<ietfdpdk>(NULL);
  }

  ietfdpdk* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ietfdpdk>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ietfdpdk& from);
  void MergeFrom(const ietfdpdk& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ietfdpdk* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string interface1 = 1;
  void clear_interface1();
  static const int kInterface1FieldNumber = 1;
  const ::std::string& interface1() const;
  void set_interface1(const ::std::string& value);
  #if LANG_CXX11
  void set_interface1(::std::string&& value);
  #endif
  void set_interface1(const char* value);
  void set_interface1(const char* value, size_t size);
  ::std::string* mutable_interface1();
  ::std::string* release_interface1();
  void set_allocated_interface1(::std::string* interface1);

  // @@protoc_insertion_point(class_scope:ietfdpdk)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr interface1_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ietfdpdk

// string interface1 = 1;
inline void ietfdpdk::clear_interface1() {
  interface1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ietfdpdk::interface1() const {
  // @@protoc_insertion_point(field_get:ietfdpdk.interface1)
  return interface1_.GetNoArena();
}
inline void ietfdpdk::set_interface1(const ::std::string& value) {
  
  interface1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ietfdpdk.interface1)
}
#if LANG_CXX11
inline void ietfdpdk::set_interface1(::std::string&& value) {
  
  interface1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ietfdpdk.interface1)
}
#endif
inline void ietfdpdk::set_interface1(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  interface1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ietfdpdk.interface1)
}
inline void ietfdpdk::set_interface1(const char* value, size_t size) {
  
  interface1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ietfdpdk.interface1)
}
inline ::std::string* ietfdpdk::mutable_interface1() {
  
  // @@protoc_insertion_point(field_mutable:ietfdpdk.interface1)
  return interface1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ietfdpdk::release_interface1() {
  // @@protoc_insertion_point(field_release:ietfdpdk.interface1)
  
  return interface1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ietfdpdk::set_allocated_interface1(::std::string* interface1) {
  if (interface1 != NULL) {
    
  } else {
    
  }
  interface1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), interface1);
  // @@protoc_insertion_point(field_set_allocated:ietfdpdk.interface1)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_test_2eproto
